//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProtokolApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class dokument
    {
        public int ID { get; set; }
        public int ID_protokola { get; set; }
        public int TipDokumenta { get; set; }
        public byte[] Dokument { get; set; }
        public string Filename { get; set; }
        public short Izbrisan { get; set; }
        public string Opis { get; set; }
        public string Racunar { get; set; }
        public Nullable<System.DateTime> DatumUnosa { get; set; }
    
        public virtual protokol protokol { get; set; }
    }
}
