//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProtokolApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class protokol
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public protokol()
        {
            this.dokument = new HashSet<dokument>();
        }
    
        public int ID { get; set; }
        public int ID_sluzbe { get; set; }
        public Nullable<int> redni_broj { get; set; }
        public Nullable<System.DateTime> datum { get; set; }
        public Nullable<System.DateTime> datum_distribucije { get; set; }
        public string predmet { get; set; }
        public string veza { get; set; }
        public string razvod { get; set; }
        public string oznaka_registratora { get; set; }
        public string oznaka_dopisa { get; set; }
        public string dostava_dopisa { get; set; }
        public string napomena { get; set; }
        public string arhiva { get; set; }
        public int izbrisan { get; set; }
        public int ID_tipa { get; set; }
        public string Racunar { get; set; }
        public string tipProtokola_SP { get; set; }
        public string brojUlaznogProtokola_SP { get; set; }
        public Nullable<System.DateTime> datumPrijema_SP { get; set; }
        public string signirano_SP { get; set; }
        public string vrstaDokumenta_sp { get; set; }
        public string sifraDokumenta_SP { get; set; }
        public string nacinPrijema_SP { get; set; }
        public string lokacijaCZK_SP { get; set; }
        public string sifraProstora_SP { get; set; }
        public string nazivKorisnikaUsluge_SP { get; set; }
        public string adresaProstora_SP { get; set; }
        public Nullable<System.DateTime> rokZaOdgovor_SP { get; set; }
        public string brojRjesenja_SP { get; set; }
        public string vrstaRjesenja_SP { get; set; }
        public string pripremioRjesenje_SP { get; set; }
        public Nullable<decimal> iznosPoRjesenju_SP { get; set; }
        public string brojIzlaznogProtokola_SP { get; set; }
        public Nullable<System.DateTime> datumOdgovora_SP { get; set; }
        public string statusReklamacije_SP { get; set; }
        public string podbroj_Kabinet { get; set; }
        public string posiljalac_Kabinet { get; set; }
        public string redniBroj_Kabinet { get; set; }
        public Nullable<int> CntDokumenata { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dokument> dokument { get; set; }
        public virtual sluzbe sluzbe { get; set; }
        public virtual tip tip { get; set; }
    }
}
