//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProtokolApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_promjena
    {
        public int ID { get; set; }
        public string naziv_polja { get; set; }
        public int ID_izvorni { get; set; }
        public Nullable<int> ID_izvorni_novi { get; set; }
        public Nullable<System.DateTime> Datum_promjene { get; set; }
        public string Promjena { get; set; }
        public string korisnikapp { get; set; }
        public string imeracunara { get; set; }
        public string ipAdresa { get; set; }
    }
}
