//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace ProtokolApp
{
    using System;
    using System.Collections.Generic;

    public partial class protokol : INotifyPropertyChanged
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public protokol()
        {
            this.dokument = new HashSet<dokument>();
        }
        public event PropertyChangedEventHandler PropertyChanged;
        private void NotifyPropertyChanged(string info)
        {
            if (PropertyChanged != null)
               
                PropertyChanged(this, new PropertyChangedEventArgs(info));
        }

        public int ID { get; set; }

        private int _ID_sluzbe;
        public int ID_sluzbe
        {
            get { return _ID_sluzbe; }
            set
            {
                if (_ID_sluzbe == value) return;
                _ID_sluzbe = value;
                NotifyPropertyChanged("ID_sluzbe");
            }
        }

        private Nullable<int> _redni_broj;
        public Nullable<int> redni_broj
        {
            get { return _redni_broj; }
            set
            {
                if (_redni_broj == value) return;
                _redni_broj = value;
                NotifyPropertyChanged("redni_broj");
            }
        }

        private Nullable<System.DateTime> _datum;
        public Nullable<System.DateTime> datum
        {
            get { return _datum; }
            set
            {
                if (_datum == value) return;
                _datum = value;
                NotifyPropertyChanged("datum");
            }
        }

        private Nullable<System.DateTime> _datum_distribucije;
        public Nullable<System.DateTime> datum_distribucije
        {
            get { return _datum_distribucije; }
            set
            {
                if (_datum_distribucije == value) return;
                _datum_distribucije = value;
                NotifyPropertyChanged("datum_distribucije");
            }
        }

        private string _predmet;

        public string predmet
        {
            get { return _predmet; }
            set
            {
                if (_predmet == value) return;
                _predmet = value;
                NotifyPropertyChanged("predmet");
            }
        }

        private string _veza;
        public string veza
        {
            get { return _veza; }
            set
            {
                if (_veza == value) return;
                _veza = value;
                NotifyPropertyChanged("veza");
            }
        }

        private string _razvod;

        public string razvod
        {
            get { return _razvod; }
            set
            {
                if (_razvod == value) return;
                _razvod = value;
                NotifyPropertyChanged("razvod");
            }
        }

        private string _oznaka_registratora;

        public string oznaka_registratora
        {
            get { return _oznaka_registratora; }
            set
            {
                if (_oznaka_registratora == value) return;
                _oznaka_registratora = value;
                NotifyPropertyChanged("oznaka_registratora");
            }
        }

        private string _oznaka_dopisa;
        public string oznaka_dopisa
        {
            get { return _oznaka_dopisa; }
            set
            {
                if (_oznaka_dopisa == value) return;
                _oznaka_dopisa = value;
                NotifyPropertyChanged("oznaka_dopisa");
            }
        }


        private string _dostava_dopisa;
        public string dostava_dopisa
        {
            get { return _dostava_dopisa; }
            set
            {
                if (_dostava_dopisa == value) return;
                _dostava_dopisa = value;
                NotifyPropertyChanged("dostava_dopisa");
            }
        }

        private string _napomena;
        public string napomena
        {
            get { return _napomena; }
            set
            {
                if (_napomena == value) return;
                _napomena = value;
                NotifyPropertyChanged("napomena");
            }
        }

        private string _arhiva;

        public string arhiva
        {
            get { return _arhiva; }
            set
            {
                if (_arhiva == value) return;
                _arhiva = value;
                NotifyPropertyChanged("arhiva");
            }
        }

        private int _izbrisan;
        public int izbrisan
        {
            get { return _izbrisan; }
            set
            {
                if (_izbrisan == value) return;
                _izbrisan = value;
                NotifyPropertyChanged("izbrisan");
            }
        }

        private int _ID_tipa;
        public int ID_tipa
        {
            get { return _ID_tipa; }
            set
            {
                if (_ID_tipa == value) return;
                _ID_tipa = value;
                NotifyPropertyChanged("ID_tipa");
            }
        }

        [ReadOnly(true)]
        public string Racunar { get; set; }


        private Nullable<int> _CntDokumenata;
        [ReadOnly(true)]
        public Nullable<int> CntDokumenata
        {
            get { return _CntDokumenata; }
            set
            {
                if (_CntDokumenata == value) return;
                _CntDokumenata = value;
                NotifyPropertyChanged("CntDokumenata");
            }
        }
        [ReadOnly(true)]

        public Nullable<System.DateTime> DatumVrijeme { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]


        public virtual ICollection<dokument> dokument { get; set; }
        public virtual sluzbe sluzbe { get; set; }
        public virtual tip tip { get; set; }
    }
}
